### ISSUE TITLE
Plan how to integrate main & mortality censues

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#1]
How do we integrate the main and mortality censuses? Some sort of integration seems the logical way to go (otherwise all ≥10cm trees would be visited twice during the year), but we need to work out the best way to do this operationally. Questions include:

- Is it better for a single team to do everything as a single integrated census, or for 1-2 people to focus on the mortality component (trees ≥10cm), adding on DBH measurements so that these trees only have to be visited once?
- Is it okay to census stems ≥10 cm and <10 cm in the same quadrat at different times? If not, we’d need to loop back and get some of the mort census info after leaf-out on the earliest-censused quadrats.

**Comment by teixeirak** [comment]
After a discussion with Jim Lutz, Dan Johnson, and @jess-shue , the plan is:
- do everything as a single integrated census
- start with spicebush-heavy quadrats (better in spring anyway), loop back later to get trees>10cm.

**Comment by teixeirak** [comment]
@jess-shue, an important remaining question here is whether we'll be able to add all the mortality census fields into the ArcGIS app. The clunky alternative would be to use the FastField app in addition to ArcGIS for the trees >10cm.

**Comment by jess-shue** [comment]
@teixeirak They can definitely be added, but yes, the clunky-ness of the extra fields will need to be tested.

**Comment by teixeirak** [comment]
Okay, thanks @jess-shue. Agree on the testing, but relieved that it should work to add them to ArcGIS (much better than having them toggle between 2 apps).

**Comment by teixeirak** [comment]
I think we can close this issue.
