### ISSUE TITLE
Dead DBH

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/2023census#13]
Hi @teixeirak,
   How would you like dead DBH to be collected? Speaking with Valentine this morning, we were thinking that DBH for dead standing trees could be collected in the same column as the DBH for living trees - that way people wouldn't have two places to enter DBH no matter the stem's status.

I know typically dead trees were not measured at most sites, but at SERC we have measured any standing stem even when dead and kept that DBH in the same column. Attempting to have a more stable version of the tables for Valentine and having the app as ready as I can soon.

**Comment by ValentineHerr** [comment]
Correct,

Please add it to your to-do list and let me know if you don't manage to get to it (along with the other things that I should be aware of), so I know I need to code it. (It is fine if you don't even try to get to it, it is mostly a backup for me, so I don't forget about this).

Thanks!

**Comment by ValentineHerr** [comment]
no worries
