### ISSUE TITLE
Spatial data and census 3 - tag issue

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/2023census#14]
Hi @ValentineHerr,
   I'm running through my R code again to add the 2022 mortality data and I've encountered a problem. I did update my local GitHub repository, so everything should be up-to-date.

In the [scbi.stem3.csv ](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_main_census/data/census-csv-files) there are two stems with the same coordinates but different species:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tag | StemTag | sp | quadrat | gx | gy | MeasureID | CensusID | dbh
-- | -- | -- | -- | -- | -- | -- | -- | --
30365 | 1 | fram | 308 | 59.6 | 141.8 | 240749 | 3 | 1001
33331 | 1 | quru | 308 | 59.6 | 141.8 | 240750 | 3 | 180

</body>

</html>

But in [scbi_stem_utm_lat_long_2018.csv](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/spatial_data/UTM%20coordinates/scbi_stem_utm_lat_long_2018.csv) there isn't a 33331 tag:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tag | StemTag | sp | quadrat | gx | gy | MeasureID | CensusID | dbh
-- | -- | -- | -- | -- | -- | -- | -- | --
30365 | 1 | fram | 308 | 59.6 | 141.8 | 240749 | 3 | 1001
30365 | 1 | fram | 308 | 59.6 | 141.8 | 240750 | 3 | 180

</body>

</html>

I think this must be a similar issue to 133461 and 131352 (can't find the issue on GitHub!) I initially thought 30365 must just have two stems, and before my update I believe 30365 was showing as having two stems in the census data. Is this a recent correction that wasn't passed to the UTM file? It looks like 133461 and 131352 are still categorized wrong in the UTM file as well.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tag | StemTag | sp | quadrat | gx | gy | MeasureID | CensusID | dbh
-- | -- | -- | -- | -- | -- | -- | -- | --
131352 | 1 | fram | 1316 | 245.5 | 303.3 | 212439 | 3 | 1020
133461 | 1 | fram | 1316 | 245.5 | 303.3 | 212440 | 3 | 321

</body>

</html>

**Comment by ValentineHerr** [comment]
Oh… I’ll fix that asap. (I closed the issue, that is why you can’t find it)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jess-shue ***@***.***>
Sent: Thursday, March 16, 2023 12:37:26 PM
To: SCBI-ForestGEO/2023census ***@***.***>
Cc: Herrmann, Valentine ***@***.***>; Mention ***@***.***>
Subject: [SCBI-ForestGEO/2023census] Spatial data and census 3 - tag issue (Issue #14)


External Email - Exercise Caution

Hi @ValentineHerr<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FValentineHerr&data=05%7C01%7Cherrmannv%40si.edu%7C84b3fe4a8ecb41d54dda08db263cba66%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638145814485615899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2YT42%2Ft%2BIcLqVz346%2BorSlVEmrcr0N4vEweJW7S5A34%3D&reserved=0>,
I'm running through my R code again to add the 2022 mortality data and I've encountered a problem. I did update my local GitHub repository, so everything should be up-to-date.

In the scbi.stem3.csv <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FSCBI-ForestGEO-Data%2Ftree%2Fmaster%2Ftree_main_census%2Fdata%2Fcensus-csv-files&data=05%7C01%7Cherrmannv%40si.edu%7C84b3fe4a8ecb41d54dda08db263cba66%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638145814485615899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vzre0xkdC5YwkQu3Lm8owlykmfIcsLzxxFv0%2BdIVk%2FY%3D&reserved=0> there are two stems with the same coordinates but different species:

<style> </style>
tag     StemTag sp      quadrat gx      gy      MeasureID       CensusID        dbh
30365   1       fram    308     59.6    141.8   240749  3       1001
33331   1       quru    308     59.6    141.8   240750  3       180

But in scbi_stem_utm_lat_long_2018.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FSCBI-ForestGEO-Data%2Fblob%2Fmaster%2Fspatial_data%2FUTM%2520coordinates%2Fscbi_stem_utm_lat_long_2018.csv&data=05%7C01%7Cherrmannv%40si.edu%7C84b3fe4a8ecb41d54dda08db263cba66%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638145814485615899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Iuzdh5%2BtocwNNKcqJapUvqy8K94lZWfjcBqScZ902G8%3D&reserved=0> there isn't a 33331 tag:

<style> </style>
tag     StemTag sp      quadrat gx      gy      MeasureID       CensusID        dbh
30365   1       fram    308     59.6    141.8   240749  3       1001
30365   1       fram    308     59.6    141.8   240750  3       180

I think this must be a similar issue to 133461 and 131352 (can't find the issue on GitHub!)

**Comment by jess-shue** [comment]
@ValentineHerr Thank you! Looks good now - that's great you got to see Erika!

**Comment by ValentineHerr** [comment]
She says hi! :-)

(Closing issue now)
