### ISSUE TITLE
Mortality - to collect or not

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/2023census#15]
Sorry @ValentineHerr, I completely skipped reading a section of my code earlier:

#### filter the data for stems >= 100 mm and mortality status 2022 of 'A', 'AU', or 'DS'

stem.mort$mortality <- with(stem.mort, ifelse(dbh >= 100 & current_year_status != "DC", 1, 0))

My thoughts on this were to skip any stems in the mortality data that are less than 100 mm DBH (the small ash etc.) and anything previously recorded as 'DC' - down and dead. Does that make sense?

**Comment by jess-shue** [comment]
Sorry, I think this is causing a problem because some trees don't have a:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



current_year_status | current_year_comment
-- | --
NA | stem not sampled, info automatically filled from previous year info



</body>

</html>

Even though they have a DBH >= 100 mm

**Comment by jess-shue** [comment]
OK, @ValentineHerr, I think I have it using this:

stem.mort$mortality <- with(stem.mort, ifelse(dbh >= 100 & current_year_status != "DC" | is.na(current_year_status), 1, 0))

Does that look correct? (Thank you for your help!)

**Comment by ValentineHerr** [comment]
Sorry for the delay, my emails were not updating...

The only thing with your statement, I think, is that it will include all `is.na(current_year_status)`, even if dbh < 100.

so I think you need:

`stem.mort$mortality <- with(stem.mort, ifelse(dbh >= 100 & (current_year_status != "DC" | is.na(current_year_status)), 1, 0))`


(I added parrenthesis around the 2 current_year_status  statement)

Also, I tend to prefer using `%in%` instead of `==` (using `!` when I need `!=`).  Doing so helps dealing with NA properly. If you do that, your code would be:

`stem.mort$mortality <- with(stem.mort, ifelse(dbh >= 100 & (!current_year_status %in% "DC" | is.na(current_year_status)), 1, 0))`

Do you have NAs in `dbh`?

**Comment by ValentineHerr** [comment]
tagging you @jess-shue in case you did not get notified of my answer (just one minute ago)

**Comment by jess-shue** [comment]
Thanks @ValentineHerr, unfortunately there are NA's in DBH and some with NA's in current_year_status, but DBH >= 100 mm.

I think I've got it now, but it wasn't a clean line of code like you wrote for me! I had to take a look at some stems individually and make a yes/no (1/0) decision. I've added list here:  [mortality_census_questions](https://github.com/SCBI-ForestGEO/2023census/blob/main/example_data/mortality_census_questions.xlsx)

I was running into the following categories that were tricky:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



dbh_2018 | current_year_status | count | mortality | notes
-- | -- | -- | -- | --
<100 | NA, A etc. | - | 0 |  
NA | NA, DC | - | 0 |  
NA | AU, DS | 6 | 1 | two stems were 0 for mortality - broken below DBH
≥100 | NA | 373 | 1 | some were DC and others DN or DS;R in last census and therefore shouldn't   be sampled
≥100 | A, AU, DS | 7447 | 1 |  
≥100 | DC | 112 | 0 |  



</body>

</html>

**Comment by ValentineHerr** [comment]
Hmmm weird status… I’ll look into that....
thanks for reporting.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ValentineHerr** [comment]
Oh, I think I misunderstood and thought you found cases where the status as actually "AU,DS" etc...

**Comment by jess-shue** [comment]
@ValentineHerr Oh, my bad! Those are just the different cases and how they should be categorized.

**Comment by ValentineHerr** [comment]
@jess-shue , I am sorry I don't have my notes from our meeting with me right now....

Did we say that `crown_position_if_dead` will be removed? if not can you remind me of the difference between between `crown_position` and `crown_position_if_dead` ? (this may be a question for @teixeirak)

**Comment by jess-shue** [comment]
@ValentineHerr  `crown_position_if_dead` will no longer be collected - there is a slight difference in the categories, but no longer will be an issue.

**Comment by jess-shue** [comment]
@ValentineHerr Yes, I just haven't added them all yet - I've been adding them from the [protocol](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/Mortality-Protocol-2022.pdf).

**Comment by teixeirak** [comment]
> And, to confirm, we are not doing emerald ash borer related measurements anymore, correct?

correct. I don't want to risk slowing down the census too much.

**Comment by ValentineHerr** [comment]
I think we can close this
