### ISSUE TITLE
update the main readme file

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/2023census#16]
@teixeirak I got the CI ready and created the "dashboard" on [the main readme file](https://github.com/SCBI-ForestGEO/2023census/blob/main/README.md).

I copied what was on the [readme file of the mortality census](https://github.com/SCBI-ForestGEO/SCBImortality#readme) but it needs to be updated (protocol, list of contributors, etc...)

**Comment by teixeirak** [comment]
This is great! Thanks, @ValentineHerr. 

I think I'll have all the participants add themselves (and their brand new GitHub name) as an exercise when we do GitHub training on Monday.

**Comment by ValentineHerr** [comment]
Good idea!
