### ISSUE TITLE
add your name in Read me file

### ISSUE THREAD

**Issue by Iriskennedy** [SCBI-ForestGEO/2023census#20]
Open [readme](https://github.com/SCBI-ForestGEO/2023census/blob/main/README.md) file, follow instructions to add your name to contributor table with `|` between different fields.

Ex: `| name | GitHub ID| position* | role |`

(note this is also just me testing out Github!)

**Comment by rmh24** [comment]
Everyone added their name

**Comment by teixeirak** [comment]
Wonderful; thank you!
