### ISSUE TITLE
Codes X, C and B

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/2023census#23]
Census crew David, @jess-shue, @Iriskennedy @CarolineTroy @rmh24 @krystalbagnaschi,

I thought we decided to use codes `C` (dead above 1.3) and `X` (broken below 1.3) and `B` (Broken above 1.3) but I am noticing you have not been using them.

The main reason I am asking is because now the DBH=0 gets flagged because they are not justified. My current check is looking in the `codes` for a justification of why dbh = 0. It is looking for `X` and 'C' (although now I am noticing that I should not look at `C` since we have decided to measure dead trees anyways).

My question is: did you guys decide to drop those codes, or did you forget to record them?
If you decided to drop them, I'll just look at the `status` of the tree and say that `DC` (or `DN`) justifies a DBH=0. 

**But what about `DS` trees? those DBH do need to be measured, to be used in the mortality census.**

**Comment by ValentineHerr** [comment]
This is what was discussed last Wed:

![image](https://user-images.githubusercontent.com/19673377/231201781-06bd00de-28ff-4d43-9df1-8cfa5a7abb43.png)

**Comment by jess-shue** [comment]
@ValentineHerr Yes, I believe it would be best to go off of the `status` column first, then use the `codes` as justification.

Stems < 100 mm (10 cm) are not assessed for mortality. So, we discussed in the field last week to not measure **DS** stems < 100 mm as it would save time and will not be used for mortality.

**Comment by ValentineHerr** [comment]
Here are my new thoughts:

1. Suzanne said:
> I check for dbhs that are 0 (not measured), they should have a code explaining why it was not measured (dead, stem broke off, stem does not reach 1.3 m in case of multiple-stemmed trees, etc.).

2. My understanding is that the status column does not get sent to ForestGEO. I know BCI does not even have that column.

3. We are requiring DBH (so we have it for mortality census), so a rightfully non measured DBH will be 0 (instead of NA, like Suzanne may expect).

Conclusion: We do need to add a code for those dead trees that have dbh=0 even if they are <100mm. Don't measure them but add the X (if status is DC) or C (is status is DS). OR I need to change them to NA.

Does that sound right @jess-shue ? We can discuss on teams in a few minute.

**Comment by ValentineHerr** [comment]
After chatting with @jess-shue, the `status` column can be sent to Suzanne, if concatenated into the `codes` column. So she will see that DS, DN or DC justify a dbh = 0. So I'll reflect that in my checks and we will be able to close this issue.
No need to change anything in the field or the data.
