### ISSUE TITLE
delete tag 199999

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/2023census#34]
tag 199999 was created by @jess-shue for a test.

I don't want to delete it myself and create a conflict.
Can one of you (@mitreds, @Iriskennedy, @krystalbagnaschi, @rmh24 or @CarolineTroy) do it and close this issue when it is done?

Thanks a lot

**Comment by jess-shue** [comment]
@ValentineHerr I am making some corrections within ArcGIS Online - quadrat names with leading zero's and deleting test trees. It looks like th raw data were last uploaded on April 18th and I was able to fix the recruits prior to that.

I will let you know later today when I have things 'ready'.

**Comment by jess-shue** [comment]
@ValentineHerr  OK, I have made some corrections, but there are still a few stems where the crew wasn't able to enter the Stem Tag because the field was locked. I'll need to download the data and look at those to be sure they should all be '2' (or not!).

**Comment by ValentineHerr** [comment]
Why all stem tag should be 2? Shouldn't they be > or equal to 2?

I just run a check on the new data and there are still a lot of duplicate Tag-StemTag combo.

**Comment by ValentineHerr** [comment]
I think 199999 was deleted so I am closing this issue

**Comment by jess-shue** [comment]
@ValentineHerr  Sorry, I wasn't being clear - they may be 2's or not, that's why I need to take a look at the data. I'm hoping to get to that soon.
