### ISSUE TITLE
question about when the main stem is DN for multiple censuses.

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/2023census#36]
@jess-shue,

I don't remember. Did you filter the data and removed stems that were e.g. "DN" for multiple censuses?
 - If yes, what would happen if it was only the main stem that was "DN" but secondary stem(s) were still alive? Would the next alive stem be the one mapped in the app and present in the tree table?
  - If not, no worries and you can close this issue.

**Comment by jess-shue** [comment]
@ValentineHerr 

I didn't filter out any stems - I was being overly cautious and wanted to avoid the issues you describe.
