### ISSUE TITLE
Big Trees

### ISSUE THREAD

**Issue by Iriskennedy** [SCBI-ForestGEO/2023census#38]
@jess-shue , @ValentineHerr we were wondering if we could add the code BT to indicate "Big Trees" on the map, and then we could have a separate map for the big trees (similar to how we have the replace tags map)

There may be more to discuss with how to handle the Big Trees @mitreds but I think this is the first step

**Comment by jess-shue** [comment]
@Iriskennedy Please see #37 

This is why I wanted to symbolize points by size. Are you simply wanting 'BT' to know when a tree needs mortality data to be taken? I think there are other ways of handling this (see other thread).

I will try to make this for you over the weekend or next week, but I am preparing to travel to Wisconsin for a week.

**Comment by Iriskennedy** [comment]
So sorry I should have specified, BT would be for trees we have to revisit with a ladder later to measure but it is not urgent at all, for now we are just leaving them in red. There may be more David wants to discuss with BTs I just wanted to put it out there so it's on our radar

**Comment by jess-shue** [comment]
@Iriskennedy @mitreds 
I have made a Big Tree layer that includes a Big Stem table. It will outline anything with the code BT in blue (hopefully this will work when you add 'BT' to the 'old stems'). 

I did some initial testing and things seemed OK. Tag 22170 in quadrat 0221 has a blue ring and when you select the point you see an option to edit the point via the 'Big Tree' table.

**Comment by ValentineHerr** [comment]
@jess-shue 
When the crew enters data in the big tree map, does that go to a different table or downloading the old_tree data should have everything?

**Comment by ValentineHerr** [comment]
I just checked and the data is just a subset of the old_tree data so no need to download the big tree data set.

Closing this issue
thanks @jess-shue!
