### ISSUE TITLE
select walkie-talkies

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#39]
@krystalbagnaschi , @Iriskennedy , @CarolineTroy , @rmh24 - Please find a set of walkie talkies that looks good. Perhaps these? https://www.outdoorgearlab.com/reviews/camping-and-hiking/walkie-talkies/rocky-talkie

**Comment by krystalbagnaschi** [comment]
Those look perfect!

**Comment by teixeirak** [comment]
I have put in a request for funds to purchase these & added them to our lab wish list.
