### ISSUE TITLE
Set up ArcGIS app

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#4]
Note: @jess-shue is working on setting up the ArcGIS app for SCBI, and expects to have it ready to test in early October.

_Originally posted by @teixeirak in https://github.com/SCBI-ForestGEO/2023census/issues/2#issuecomment-1240770571_

**Comment by teixeirak** [comment]
Note: we will need to include the mortality census fields in the ArcGIS app.

The app will, of course, require testing.

**Comment by ValentineHerr** [comment]
@jess-shue, from our call on Friday it sounded like you needed a push with this. If you don't get it from someone who knows the app, I'd be happy to have a look with you, so I can at least be a moral support to you :-)

**Comment by ValentineHerr** [comment]
@jess-shue, something to keep in mind for the next time we do this (in 5 years at SCBI or before at other sites):

It helps when the column names are more general, so we can re-use scripts easily from one census to the next.

I am talking about the names that have the year in them:

- `XXX_2018` would become `XXX_previousCensus`
- `XXX_2021` would become `XXX_previousMortalityCensus` (reminder to make sure now it is 2022 - it is still 2021 in the example data)
- `XXX_2023` would become `XXX_currentCensus`
