### ISSUE TITLE
New Mortality Tree Error

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/2023census#42]
Hi @jess-shue,

Censused trees that have newly grown to >= 100 mm dbh that were < 100 dbh in 2022 do not have the mortality drop down.  Would mortality be able to be added to these trees easily? 

Let me know your thoughts,
Thanks

**Comment by teixeirak** [comment]
Thanks for paying attention to this, @emacmonigle . We've defined the mortality census to include stems ≥100 mm in the last census (mainly a practical consideration so we can define the sample without remeasuring trees). We could potentially catch those trees this year, but if it's at all complicated, I'd like to stick with the cohort from the 2018 census, and next year all the stems ≥100 mm from this census will be monitored.

**Comment by teixeirak** [comment]
Note that in the 2018 mortality census, we did not include the trees that had grown into the ≥ 100 mm class since the 2013 census. It wouldn't hurt to do that this year, but not necessary.

**Comment by emacmonigle** [comment]
@teixeirak Sounds great! We can mark those trees as complete then.

**Comment by jess-shue** [comment]
Thanks @teixeirak, that was my thought as well - this is the first time new census measurements are coming in and stems are reaching 10 cm DBH. As we haven't added these 'recruits' in the past, I think Krista's previous comment of adding them for next year's mortality census is best.

**Comment by teixeirak** [comment]
> @teixeirak Sounds great! We can mark those trees as complete then.

yup!
