### ISSUE TITLE
Need H Code for ArcGIS App

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/2023census#44]
@jess-shue Hi jess, in the most recent version of the protocol there is a code H - hollow stem. This is not reflected in the app and I was wondering if that code could be updated for use in the census as we continue to make more progress.

**Comment by jess-shue** [comment]
@emacmonigle is this for mortality or for the regular census? 
@mageeluke, @djj4tree, @teixeirak are sites using an 'H' code for hollow stem?
Thanks,
Jess

**Comment by teixeirak** [comment]
The "H" code would be new. Was there a decision to add that?

**Comment by djj4tree** [comment]
I believe we use HS for hollow stem.

**Comment by jess-shue** [comment]
OK, I can add that - I must not have access to the most up-to-date protocol (or didn't find it!).
