### ISSUE TITLE
remove stems we know are missing

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#46]
@jess-shue , @ValentineHerr ,

It would help the census team if we remove stems that we know are missing: status WR (wire removed), DT (dead tag found), for DN for two (5-yr) censuses in a row. We might also consider removing stems found as DN in mortality census for a few years in a row.

We had some discussion as to whether this should be applied on a stem or tree basis. @Iriskennedy , @rmh24 , @CarolineTroy , @krystalbagnaschi , @emacmonigle , please weigh in.

**Comment by jess-shue** [comment]
@teixeirak, @ValentineHerr 

As I am not working from Python code, this would be a heavy lift, and in my opinion not a good idea at this point in the census. The current labels already show the previous codes (DN, DS, etc.). I may be able to change the symbology (color/shape etc.) of the points, but otherwise I would basically have to re-build the app to make this happen.

I understand that working in the field with 2018 data when there is newer information from the mortality censuses (and without dead stems removed) can be frustrating - I have done it myself - but initially we had kept dead stems in the data in case of previous errors.

This is something we should have discussed further during setup. Please let me know how seriously this is needed, but I would basically end up building a new app.

**Comment by teixeirak** [comment]
I'd envision that perhaps a simple list of stems meeting these criteria (separate from app) might be useful, but I'm not sure.  @Iriskennedy , @rmh24 , @CarolineTroy , @krystalbagnaschi , @emacmonigle , please comment.

**Comment by teixeirak** [comment]
@Iriskennedy , @rmh24 , @CarolineTroy , @krystalbagnaschi , @emacmonigle , would it be helpful to get a list of these stems and then mark as not found ahead of censusing each quadrat? This could be done from the lab and save time in the field.

**Comment by jess-shue** [comment]
@teixeirak As I mentioned above, I may be able to do something with the symbology, or how the points appear as well if the list of stems were created. If Valentine could make the list, I'd be willing to attempt something on the appearance side, but I can't promise it will work. Completely removing them from the data would require the full re-build.

**Comment by teixeirak** [comment]
Thanks, @jess-shue! I think that altering the symbology could be very helpful., and a better solution than removing them altogether. @Iriskennedy , @rmh24 , @CarolineTroy , @krystalbagnaschi , @emacmonigle ,  please let us know ASAP if this sounds like  a good solution to you.

**Comment by teixeirak** [comment]
@ValentineHerr , since you'll be out soon, let's go ahead and make the lists (assuming you can do this quickly, which I think you can). Let's make lists of:
- trees marked DN for two main (5-yr) censuses in a row
- trees marked DN for two mortality censuses in a row, and marked DS or DC at some point before that. 

The first category is higher priority if you only have time for that.

**Comment by ValentineHerr** [comment]
@jess-shue 
Here is the list of 838 tags and stemtags that were marked DN at census 2 and 3:
[DNfor2mainCensus.csv](https://github.com/SCBI-ForestGEO/2023census/files/12100300/DNfor2mainCensus.csv)

@teixeirak and @jess-shu, a quick look at mortality censuses showed no cases of trees marked "DN" two censuses in a row, so the second category would be empty.

**Comment by jess-shue** [comment]
@ValentineHerr Thank you for putting that together!

@Iriskennedy @emacmonigle @rmh24 @CarolineTroy @krystalbagnaschi 
Realizing it is only 838 stems, is it worth putting another layer together for you? I will gladly do it, but I want to make sure this is truly helpful before working through things. Thank you!

**Comment by krystalbagnaschi** [comment]
Thank you very much @ValentineHerr! Is there any way we could get a list of those marked with the code TR (tag removed) as well? Only if it's easy and you have time of course.

@jess-shue the list should be plenty - we're thinking that this is work that could be done remotely on rainy days etc so the color of the points changing to finished should be enough of a distinction on the map when we get to the field. Thank you!

**Comment by jess-shue** [comment]
@krystalbagnaschi @Iriskennedy @emacmonigle @rmh24 @CarolineTroy @krystalbagnaschi and @ValentineHerr 

I added a file of stems with code 'TR' as [TRstems.csv](https://github.com/SCBI-ForestGEO/2023census/tree/main/raw_data).

I wasn't sure how Valentine linked to the DN file above, so sorry if adding it to the raw_data folder isn't the best option.
