### ISSUE TITLE
QAQC for new raw data failed 7/21/23

### ISSUE THREAD

**Issue by CarolineTroy** [SCBI-ForestGEO/2023census#48]
@ValentineHerr When I uploaded the raw data on Friday, the QAQC action failed. Do you have any advice on how to resolve this?

**Comment by krystalbagnaschi** [comment]
@ValentineHerr Hi Valentine - I tried to push the raw data from my account today and it is still failing. Should we pause on pushing data for now, and do you have any recommendations on how to fix this issue?

**Comment by mageeluke** [comment]
@CarolineTroy, @teixeirak, @krystalbagnaschi , the CI seems to be working now: there was a tree code listed as a StemTag.

**Comment by teixeirak** [comment]
many, many thanks @mageeluke!
