### ISSUE TITLE
Mortality tree data disappearing

### ISSUE THREAD

**Issue by Iriskennedy** [SCBI-ForestGEO/2023census#53]
Hello, we have discovered an issue with some of the mortality trees. With the new mortality layer there is an orange circle indicating the mortality trees and when we mark the circle as complete it turns blue. We have just noticed that with some of the trees where we turned the circle orange to blue, all the data- census and mortality- is gone except for the status. An example of a tree like this is 131080. We are currently investigating this but I wanted to loop you everyone in.

We think we have tracked the date of the error to October 11.

**Comment by Iriskennedy** [comment]
Hello, we could do a short zoom on Thursday at 2 if that works for you.

**Comment by jess-shue** [comment]
Hi @Iriskennedy,  below is a Zoom link to meet at 2 pm. I'm testing things now and doing some Googling for answers, nothing quite matches this issue though. Looking forward to seeing everyone soon:

Jessica Shue is inviting you to a scheduled Zoom meeting.

Topic: SCBI - FieldMaps data issue
Time: Oct 26, 2023 02:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://smithsonian.zoom.us/j/85079491033?pwd=TjZnMGNKdEcraXgwRUtMMUtEbm1CQT09

Meeting ID: 850 7949 1033
Passcode: 065557
One tap mobile
+16469313860,,85079491033#,,,,*065557# US
+13017158592,,85079491033#,,,,*065557# US (Washington DC)

**Comment by jess-shue** [comment]
Thank you for discussing things with me yesterday. I wasn't able to recover the lost data as it was cleared before being sent to ArcGIS Online. But, you have things under control and can continue to collect data. Closing this issue.
