### ISSUE TITLE
Running list of errors that can't be fixed in field

### ISSUE THREAD

**Issue by Iriskennedy** [SCBI-ForestGEO/2023census#57]
- Tree 152044, has in notes : "stems switched in past mortality census" we may have discussed this already but want to make sure it is correct.

- 140799 stem 5 is giving a missed stem error but it does not exist on the ipads

We may add a few more to this after pushing some warning corrections today

**Comment by ValentineHerr** [comment]
@Iriskennedy issue with 140799 stem 5 is resolved.

**Comment by ValentineHerr** [comment]
I'll add the other issue in the mortality repo and deal with it later. so closing this.
