### ISSUE TITLE
change notes so the pattern is clear for species change

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/2023census#63]
@Iriskennedy, @krystalbagnaschi or @rmh24,

I am working on reconciling the species ids.
Some were actually edited in the app, but others are just mentioned in the notes.

I can see that there are two patterns in the notes:
  1. "Species is not AAAA is BBBB" (most common pattern) 
  2. "Species is BBBB, not AAA" (least common pattern).

To make it easier/safer for the code to implement those changes, could you edit the following 10 notes to follow pattern 1? (including for moru, the last one in the list, change to "Species is not unk is MORU")

tag|StemTag|sp|notes_current
--|--|--|--
132317|1|cato|Species is pist not cato
132376|1|amar|Species is CAGL not AMAR
132416|1|cato|Species is CAGL not CATO
152496|1|nysy|Species is QUPR, not NYSY
153740|1|libe|Species is ULRU not LIBE
23508|1|libe|Species is CACA not LIBE
33527|1|elum|Species is LIBE not ELUM
33674|1|libe|Species is CACA not LIBE
72028|1|qupr|Species is QURU, not QUPR
151432|1|unk|Species is MORU!

**Comment by ValentineHerr** [comment]
also here is an ambiguous case:

tag 23445: "Species is not ELUM not ACNE" --> please fix

**Comment by krystalbagnaschi** [comment]
These edits have been pushed to github

**Comment by ValentineHerr** [comment]
@krystalbagnaschi it would help me greatly if you could copy the comment about species being caca that is written for 53030 stem 2 into the 53030 main stem table.
Thanks!

**Comment by ValentineHerr** [comment]
tag 53030 --> add comment about species change to main stem.

**Comment by ValentineHerr** [comment]
Census crew: in a few minutes the QA/QC will be updated. Please fix the few cases where there was a typo in the species name. You can ignore `moru`, I'll need to add that one to our species list.

**Comment by ValentineHerr** [comment]
@krystalbagnaschi @Iriskennedy @krystalbagnaschi sorry, there was an issue with CI... fixed now but here is the list of species to fix (in field and also in comment when needed).
Ignore moru.


tag|species|notes_current
--|--|--
110943|live|Id tag on stem 5, species is not litu is live
144178|cosp|
163250|iibe|
151432|moru|
110943|live|
110943|live|
110943|live|
110943|live|

**Comment by ValentineHerr** [comment]
@krystalbagnaschi @Iriskennedy @krystalbagnaschi friendly re-tag so one of you can fix the 4 individuals that have a typo in their new species id (ignore moru). Thanks!

**Comment by ValentineHerr** [comment]
@krystalbagnaschi, thanks for pushing these fixes!

Is it possible you forgot 163250? it still shows up as iibe in the error report...

**Comment by Iriskennedy** [comment]
@ValentineHerr I just checked 163250 on the ipad and it had libe for species, I'm going to push the data again- maybe that didn't work for some reason?

**Comment by ValentineHerr** [comment]
Thanks @Iriskennedy! We figured it was an uppercase "i" which looks exactly like a lower case "L": I vs l
Tricky!

Reminder: when you push a commit that is related to an issue, it is good practice to reference the issues with `#` in the commit title or message, so we can see if/when something was done about the issue.

Closing this now.
