### ISSUE TITLE
create list of tag numbers that need replacement

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#7]
@ValentineHerr , could you please create a simple comma-separated list of all trees that need new tags ("RT" code in the "Tag maintenance" field of the mortality census data). This will go to @jess-shue , who will order replacement tags.

**Comment by ValentineHerr** [comment]
working on this now

**Comment by ValentineHerr** [comment]
What does "NN" mean in "Tag maintenance" ?

**Comment by teixeirak** [comment]
I believe that's "nail needed". Right @jess-shue ?

**Comment by ValentineHerr** [comment]
@jess-shue, here is the list of tags with "RT" code. Let me know if you want it in a file or if copy-pasting from here is better for you (I can also easily remove the quotes if needed).

# List tags with `RT` codes 
"22576", "22579", "22589", "22592", "22598", "22604", "22614", 
"72447", "72457", "160788", "160940", "160942", "201087", "22371", 
"22403", "80012", "80013", "80026", "80045", "80050", "140809", 
"140818", "140467", "200553", "200555", "10469", "10473", "10480", 
"190726", "202076", "202080", "202095", "141079", "121449", "190767", 
"190775", "92245", "90529", "182499", "131154", "171197", "50341", 
"30570", "30489", "30541", "30560", "30562", "10664", "10671", 
"10675", "10678", "150890", "152393", "152410", "152429", "101094", 
"132064", "132077", "80645", "132531", "122278", "141058", "140931", 
"140934", "112495", "132235", "180036", "180214", "22097", "22111", 
"62265", "62268", "111230", "180634", "180644", "62426", "62427", 
"172225", "202756", "202758", "202777", "202779", "192144", "192146", 
"192151", "192183", "80675", "80753", "80763", "180674", "200567", 
"151158", "122561", "131298", "131325", "131337", "152069", "101227", 
"160811", "160813", "150805", "200108", "200135", "50507", "182151", 
"120162", "120454", "120069", "142281", "112309", "142612", "82237", 
"10530", "10543", "72170", "142520", "10163", "151072", "151082", 
"72324", "72330", "12195", "12197", "12203", "12211", "12213", 
"12222", "151618", "151663", "151666", "131362", "151190", "72337", 
"22178", "22186", "22198", "22207", "22214", "12242", "12245", 
"72189", "72198", "72003", "72024", "72027", "72028", "72039", 
"72041", "171450", "22302", "22313", "122437", "122478", "122482", 
"32498", "192113", "192114", "192121", "152634", "152645", "142601", 
"142192", "110797", "70662", "202004", "202203", "92016", "92029", 
"130785", "131044", "160777", "160922", "160926", "160930", "60160", 
"201156", "201200", "192008", "192011", "192206", "192209", "192213", 
"171306", "182385", "182395", "182580", "12310", "202545", "202555", 
"132204", "180506", "180508", "202183", "202646", "202686", "62066", 
"172449", "100070", "170695", "171087", "10280", "10284", "10285", 
"10287", "10424", "10427", "92424", "92427", "92435", "92438", 
"12427", "12431", "12437", "12460", "12472", "12474", "132002", 
"132025", "60462", "60585", "60590", "152483", "180790", "180794", 
"70008", "161504", "70110", "70126", "132412", "112170", "112180", 
"112188", "22257", "22274", "22293", "90634", "101215", "13105", 
"162583", "162593", "162595", "202299", "122121", "122140", "91351", 
"91468", "12032", "142291", "202162", "160667", "160719", "22061", 
"22063", "22064", "22066", "22070", "22121", "22127", "22129", 
"22138", "202529", "202538", "202788", "202791", "202902", "190814", 
"190826", "190827", "190912", "190922", "62328", "12089", "12103", 
"12110", "12114", "12118", "22629", "22630", "22647", "182695", 
"122490", "72215", "72220", "200189", "200198", "92464", "132285", 
"132371", "70589", "70595", "52151", "172158", "172371", "172377", 
"12490", "101176", "101259", "12001", "162402", "201338", "201437", 
"22545", "22564", "22565", "22571", "182668", "182671", "32092", 
"150566", "150778", "200389", "122550", "50499", "60160", "60353", 
"122570", "161012", "152521", "12354", "12370", "72106", "72116", 
"190574", "190777", "190779", "52046", "52047", "52049", "192254", 
"180808", "180818", "180973", "22485", "22491", "22514", "22515", 
"22522", "160788", "160940", "160942", "190353", "190394", "140847", 
"141037", "170037", "131221", "162417", "162511", "142640", "202260", 
"200613", "90751", "90752", "62297", "62303", "180832", "180842", 
"180992", "180999", "102492", "112250", "22336", "172325", "172326", 
"12121", "12123", "92074", "111041", "111059", "111338", "72280", 
"80491", "171000", "150600", "201279", "201303", "70371", "12058", 
"200676", "182050", "182054", "180235", "142005", "182406", "182627", 
"12581", "12644", "12672", "190597", "190794", "190809", "192128", 
"192132", "192141", "150981", "192595", "192700", "192718", "141144", 
"102322", "172343", "172367", "192525", "150048", "150306", "130165", 
"130179", "22244", "22247", "32072", "72383", "171336", "12169", 
"12173", "12178", "122230", "182033", "182038", "182483", "182494", 
"82173", "172404", "172413", "52443", "52451", "52295", "160698", 
"10581", "52071", "121463", "121468", "142363", "80009", "80109", 
"80118", "70606", "70655", "192024", "192218", "192219", "82138", 
"82146", "82158", "90136", "111207", "111217", "192374", "121322", 
"102150", "22018", "22026", "22041", "22416", "22434", "22452", 
"22465", "160693", "160814", "82341", "82353", "142380", "130778", 
"182413", "182421", "70407", "70421", "62247", "62248", "190082", 
"190090", "90010", "90012", "10436", "10445", "10517", "10527", 
"20799", "20811", "30483", "200858", "82402", "130120", "50612", 
"161524", "161572", "152588", "162566", "162570", "152215", "140344", 
"202129", "202130", "202337", "140069", "132465", "132466", "72071", 
"72072", "72098", "100168", "102107", "202963", "82094", "82076", 
"80329", "160777", "160922", "160926", "160930", "130393", "90683", 
"90702", "172577", "172614", "170801", "50571", "50573", "53152", 
"12274", "172436", "172437", "140701", "62452", "62457", "70169", 
"182018", "182207", "182208", "52225", "101313", "160765", "102241", 
"102244", "152679", "32417", "32440", "190712", "190716", "10013", 
"10016", "10021", "10157", "192077", "192258", "110957", "110985", 
"60040", "60250", "10602", "10613", "10619", "10621", "50563", 
"50647", "122176", "160954", "102470", "10045", "10196", "151136", 
"151148", "150938", "150940", "150951", "70022", "150146", "150147", 
"70454", "70552", "180918", "180931", "82201", "202945", "202949", 
"172400", "60444", "171225", "132257", "132326", "132328", "192562", 
"192692", "122028", "40093", "30080", "40563", "40873", "30163", 
"20734", "20755", "20760", "30041", "30047", "50038", "40569", 
"40571", "40001", "40077", "50160", "50288", "40135", "20027", 
"40485", "20392", "20600", "40460", "40465", "20712", "20676", 
"20678"

**Comment by ValentineHerr** [comment]
> I believe that's "nail needed". Right @jess-shue ?

Do you need a list of these too?  If not, prepare at least 413 nails to take in the field.

**Comment by teixeirak** [comment]
We don't need that list yet, although it may be helpful to either print it out or have it show up as a field in the ArcGIS app.... not sure what will be easiest.

**Comment by ValentineHerr** [comment]
Ok, I ended up adding two files with both lists of tags, in the main folder of this repo.

**Comment by teixeirak** [comment]
Thanks!

**Comment by teixeirak** [comment]
> > I believe that's "nail needed". Right @jess-shue ?
> 
> Do you need a list of these too? If not, prepare at least 413 nails to take in the field.

@ValentineHerr , does this include the ones that need the new tags, or is that in addition?

**Comment by jess-shue** [comment]
@teixeirak @ValentineHerr 
Sorry I never responded previously, the 'NN' can be new nail or wire - so the supply needed depends on the DBH of the tree. Not sure about adding this to the app, but I'll add it to my list of edits/to-do's.

**Comment by teixeirak** [comment]
In this case we're talking  about just >10cm DBH trees. 

I don't know that's its needed for the main census app this year. We did it in the 2022 mort census to have the info for this census.
