### ISSUE TITLE
clarify color coding system for stems

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/2023census#8]
@gonzalezeb , can you please tell us the system, or tell me where to find it?

**Comment by gonzalezeb** [comment]
Details on measuring stems are in the file called "Quickguide_Recensus SCBI 2018.v1" (in the internal T drive)

Here the coding:
1.	White – Second largest stem
2.	Blue – Third largest stem.
3.	Red – Fourth largest stem
4.	Green – Fifth largest stem
5.	Do not worry about the rest of the stems, but make an effort in the field to match stem size.
